<?php

$I = new ApiTester($scenario);

$I->comment('Testing with empty literal null');
$uri = $I->getMyBaseUri() . '/cast/empty';
$yamlFilename = 'castNull.yaml';
$I->performLogin(getenv('TESTER_DEVELOPER_NAME'), getenv('TESTER_DEVELOPER_PASS'));
$I->createResourceFromYaml($yamlFilename);

$I->wantTo('Test cast null to array.');
$I->sendGet($uri, ['data_type' => 'array']);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => [],
]);

$I->wantTo('Test cast null to boolean.');
$I->sendGet($uri, ['data_type' => 'boolean']);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => null,
]);

$I->wantTo('Test cast null to empty.');
$I->sendGet($uri, ['data_type' => 'empty']);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => null,
]);

$I->wantTo('Test cast null to float.');
$I->sendGet($uri, ['data_type' => 'float']);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => null,
]);

$I->wantTo('Test cast null to html.');
$I->sendGet($uri, ['data_type' => 'html']);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => [
        'html' => [
            ['_lang' => 'en-us'],
            [
                'head' => [
                    [
                        'meta' => [
                            ['_charset' => 'utf-8'],
                        ],
                    ], [
                        'title' => [
                            ['#text' => 'HTML generated by ApiOpenStudio'],
                        ],
                    ],
                ],
            ], [
                "body" => [
                    [
                        "div" => [
                            ["#text" => "null"],
                        ],
                    ],
                ],
            ],
        ],
    ],
]);

$I->wantTo('Test cast null to image.');
$I->sendGet($uri, ['data_type' => 'image']);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => null,
]);

$I->wantTo('Test cast null to integer.');
$I->sendGet($uri, ['data_type' => 'integer']);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => null,
]);

$I->wantTo('Test cast null to json.');
$I->sendGet($uri, ['data_type' => 'json']);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => null,
]);

$I->wantTo('Test cast null to text.');
$I->sendGet($uri, ['data_type' => 'text']);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => null,
]);

$I->wantTo('Test cast null to xml.');
$I->sendGet($uri, ['data_type' => 'xml']);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => [
        'apiOpenStudioWrapper' => [],
    ],
]);

$I->tearDownTestFromYaml($yamlFilename);

$I->comment('Testing with empty string literal');
$uri = $I->getMyBaseUri() . '/cast/empty';
$yamlFilename = 'castEmptyString.yaml';
$I->createResourceFromYaml($yamlFilename);

$I->wantTo('Test cast empty string to array.');
$I->sendGet($uri, ['data_type' => 'array']);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => [],
]);

$I->wantTo('Test cast empty string to boolean.');
$I->sendGet($uri, ['data_type' => 'boolean']);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => null,
]);

$I->wantTo('Test cast empty string to empty.');
$I->sendGet($uri, ['data_type' => 'empty']);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => null,
]);

$I->wantTo('Test cast empty string to float.');
$I->sendGet($uri, ['data_type' => 'float']);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => null,
]);

$I->wantTo('Test cast empty string to html.');
$I->sendGet($uri, ['data_type' => 'html']);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => [
        'html' => [
            ['_lang' => 'en-us'],
            [
                'head' => [
                    [
                        'meta' => [
                            ['_charset' => 'utf-8'],
                        ],
                    ], [
                        'title' => [
                            ['#text' => 'HTML generated by ApiOpenStudio'],
                        ],
                    ],
                ],
            ], [
                "body" => [
                    [
                        "div" => [
                            ["#text" => "null"],
                        ],
                    ],
                ],
            ],
        ],
    ],
]);

$I->wantTo('Test cast empty string to image.');
$I->sendGet($uri, ['data_type' => 'image']);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => null,
]);

$I->wantTo('Test cast empty string to integer.');
$I->sendGet($uri, ['data_type' => 'integer']);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => null,
]);

$I->wantTo('Test cast empty string to json.');
$I->sendGet($uri, ['data_type' => 'json']);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => null,
]);

$I->wantTo('Test cast empty string to text.');
$I->sendGet($uri, ['data_type' => 'text']);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => null,
]);

$I->wantTo('Test cast empty string to xml.');
$I->sendGet($uri, ['data_type' => 'xml']);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => [
        'apiOpenStudioWrapper' => [],
    ],
]);

$I->tearDownTestFromYaml($yamlFilename);
