<?php

$I = new ApiTester($scenario);

$json = "true";

$xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<apiOpenStudioWrapper><item>true</item></apiOpenStudioWrapper>";

// phpcs:ignore
$html = "<!DOCTYPE html>\n<html lang=\"en-us\"><head><meta charset=\"utf-8\" /><title>HTML generated by ApiOpenStudio</title></head><body><div>true</div></body></html>";

$I->performLogin(getenv('TESTER_DEVELOPER_NAME'), getenv('TESTER_DEVELOPER_PASS'));
$yamlFilename = 'textBoolean.yaml';
$uri = $I->getMyBaseUri() . '/text/boolean';
$I->createResourceFromYaml($yamlFilename);

// json - application/json
$I->wantTo('Test a html string with accept: application/json.');
$I->haveHttpHeader('Accept', 'application/json');
$I->sendGet($uri);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => $json,
]);
$I->deleteHeader('Accept');

// xml - application/xml
$I->wantTo('Test a html string with accept: application/xml.');
$I->haveHttpHeader('Accept', 'application/xml');
$I->sendGet($uri);
$I->seeResponseCodeIs(200);
$I->seeResponseIsXml();
$I->seeResponseContains($xml);
$I->deleteHeader('Accept');

// xml - text/xml
$I->wantTo('Test a html string with accept: text/xml.');
$I->haveHttpHeader('Accept', 'text/xml');
$I->sendGet($uri);
$I->seeResponseCodeIs(200);
$I->seeResponseIsXml();
$I->seeResponseContains($xml);
$I->deleteHeader('Accept');

// text = text/plain
$I->wantTo('Test a html string with accept: text/plain.');
$I->haveHttpHeader('Accept', 'text/plain');
$I->sendGet($uri);
$I->seeResponseCodeIs(200);
$I->seeResponseContains($json);
$I->deleteHeader('Accept');

// html = text/html
$I->wantTo('Test a html string with accept: text/html.');
$I->haveHttpHeader('Accept', 'text/html');
$I->sendGet($uri);
$I->seeResponseCodeIs(200);
$I->seeResponseIsXml();
$I->seeResponseContains($html);
$I->deleteHeader('Accept');

$I->haveHttpHeader('Accept', 'application/json');
$I->tearDownTestFromYaml($yamlFilename);
