<?php

$I = new ApiTester($scenario);
$I->performLogin(getenv('TESTER_DEVELOPER_NAME'), getenv('TESTER_DEVELOPER_PASS'));
$yamlFilename = 'arrayAssociativeSimple.yaml';
$uri = $I->getMyBaseUri() . '/array/associative/simple';
$I->createResourceFromYaml($yamlFilename);

// json - application/json
$I->wantTo('Test a simple associative array with accept: application/json.');
$I->haveHttpHeader('Accept', 'application/json');
$I->sendGet($uri);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => [
        'one' => 'this',
        'two' => 'is',
        'three' => 'an',
        'four' => 'associative',
        'five' => 'array',
    ],
]);
$I->deleteHeader('Accept');

// xml - application/xml
$xml = "<?xml version=\"1.0\"?>\n";
$xml .= '<apiOpenStudioWrapper>';
$xml .= '<one>this</one><two>is</two><three>an</three><four>associative</four><five>array</five>';
$xml .= '</apiOpenStudioWrapper>';
$I->wantTo('Test a simple associative array with accept: application/xml.');
$I->haveHttpHeader('Accept', 'application/xml');
$I->sendGet($uri);
$I->seeResponseCodeIs(200);
$I->seeResponseIsXml();
$I->seeResponseContains($xml);
$I->deleteHeader('Accept');

// xml - text/xml
$I->wantTo('Test a simple associative array with accept: text/xml.');
$I->haveHttpHeader('Accept', 'text/xml');
$I->sendGet($uri);
$I->seeResponseCodeIs(200);
$I->seeResponseIsXml();
$I->seeResponseContains($xml);
$I->deleteHeader('Accept');

// text = text/plain
$I->wantTo('Test a simple associative array with accept: text/plain.');
$I->haveHttpHeader('Accept', 'text/plain');
$I->sendGet($uri);
$I->seeResponseCodeIs(400);
$I->seeResponseContains('Error: Cannot cast array to text');
$I->deleteHeader('Accept');

// html = text/html
$html = "<!DOCTYPE html>\n";
$html .= '<html lang="en-us"><head><meta charset="utf-8" /><title>HTML generated by ApiOpenStudio</title></head>';
$html .= '<body><dl>';
$html .= '<dt>one</dt><dd>this</dd>';
$html .= '<dt>two</dt><dd>is</dd>';
$html .= '<dt>three</dt><dd>an</dd>';
$html .= '<dt>four</dt><dd>associative</dd>';
$html .= '<dt>five</dt><dd>array</dd>';
$html .= '</dl></body></html>';
$I->wantTo('Test a simple associative array with accept: text/html.');
$I->haveHttpHeader('Accept', 'text/html');
$I->sendGet($uri);
$I->seeResponseCodeIs(200);
$I->seeResponseIsXml();
$I->seeResponseContains($html);
$I->deleteHeader('Accept');

$I->haveHttpHeader('Accept', 'application/json');
$I->tearDownTestFromYaml($yamlFilename);
