<?php

$I = new ApiTester($scenario);
$I->performLogin(getenv('TESTER_DEVELOPER_NAME'), getenv('TESTER_DEVELOPER_PASS'));
$yamlFilename = 'arrayAssociativeNested.yaml';
$uri = $I->getMyBaseUri() . '/array/associative/nested';
$I->createResourceFromYaml($yamlFilename);

// json - application/json
$I->wantTo('Test a simple associative array with accept: application/json.');
$I->haveHttpHeader('Accept', 'application/json');
$I->sendGet($uri);
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
$I->seeResponseContainsJson([
    'result' => 'ok',
    'data' => [
        'one' => [
            'one_one' => 'this',
            'one_two' => 'is',
            'one_three' => 'an',
        ],
        'two' => [
            'two_one' => 'associative',
            'two_two' => 'array',
        ],
    ],
]);
$I->deleteHeader('Accept');

// xml - application/xml
$xml = "<?xml version=\"1.0\"?>\n";
$xml .= '<apiOpenStudioWrapper>';
$xml .= '<one><one_one>this</one_one><one_two>is</one_two><one_three>an</one_three></one>';
$xml .= '<two><two_one>associative</two_one><two_two>array</two_two></two>';
$xml .= '</apiOpenStudioWrapper>';
$I->wantTo('Test a simple associative array with accept: application/xml.');
$I->haveHttpHeader('Accept', 'application/xml');
$I->sendGet($uri);
$I->seeResponseCodeIs(200);
$I->seeResponseIsXml();
$I->seeResponseContains($xml);
$I->deleteHeader('Accept');

// xml - text/xml
$I->wantTo('Test a simple associative array with accept: text/xml.');
$I->haveHttpHeader('Accept', 'text/xml');
$I->sendGet($uri);
$I->seeResponseCodeIs(200);
$I->seeResponseIsXml();
$I->seeResponseContains($xml);
$I->deleteHeader('Accept');

// text = text/plain
$I->wantTo('Test a simple associative array with accept: text/plain.');
$I->haveHttpHeader('Accept', 'text/plain');
$I->sendGet($uri);
$I->seeResponseCodeIs(400);
$I->seeResponseContains('Error: Cannot cast array to text');
$I->deleteHeader('Accept');

// html = text/html
$html = "<!DOCTYPE html>\n";
$html .= '<html lang="en-us"><head><meta charset="utf-8" /><title>HTML generated by ApiOpenStudio</title></head><body>';
$html .= '<dl>';
$html .= '<dt>one</dt>';
$html .= '<dd>';
$html .= '<dl>';
$html .= '<dt>one_one</dt><dd>this</dd>';
$html .= '<dt>one_two</dt><dd>is</dd>';
$html .= '<dt>one_three</dt><dd>an</dd>';
$html .= '</dl>';
$html .= '</dd>';
$html .= '<dt>two</dt>';
$html .= '<dd>';
$html .= '<dl>';
$html .= '<dt>two_one</dt><dd>associative</dd>';
$html .= '<dt>two_two</dt><dd>array</dd>';
$html .= '</dl>';
$html .= '</dd>';
$html .= '</dl>';
$html .= '</body></html>';
$I->wantTo('Test a simple associative array with accept: text/html.');
$I->haveHttpHeader('Accept', 'text/html');
$I->sendGet($uri);
$I->seeResponseCodeIs(200);
$I->seeResponseIsXml();
$I->seeResponseContains($html);
$I->deleteHeader('Accept');

$I->haveHttpHeader('Accept', 'application/json');
$I->tearDownTestFromYaml($yamlFilename);
